### ISSUE TITLE
There may be an error on Line 140 of Train.py?

### ISSUE THREAD

**Issue by superpig99** [anpwu/DeR-CFR#1]
Hi, from what I understand, test_y0 and test_y1 in Line 138 mean test_yf and test_ycf, so, pehe in Line 140 may be not right?

**Comment by anpwu** [comment]
> 
Sorry for the delayed response. Please refer to the definition of test_dict, where we set the treatment as all zero. Therefore, test_yf is equivalent to test_y0:

'''
    if FLAGS.y_is_binary:
                     test_t = test['t']
    else: 
                    test_t = test['t'] - test['t']
    test_dict = {net.x: test['x'], net.t: test_t, net.y: test['y'],
                 net.do_in: 1.0, net.do_out: 1.0, net.p_t: 0.5, net.I: test['I'],
                 net.t_threshold: t_threshold, net.y_threshold: y_threshold}
'''

**Comment by superpig99** [comment]
Oh, I see! 👍👍👍Thanks for your help :)🌸🌸🌸
